name: Checkmarx Scan

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ "main" ]
  workflow_dispatch:
  
permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder:
          - crew
          - flight-simulator
          - navigation
          - ticket-booking
          - warp-drive-manager
        include:
          - folder: crew
            project_name: crew
            tag: large-monorepo:crew
          - folder: flight-simulator
            project_name: flight-simulator
            tag: large-monorepo:flight-simulator
          - folder: navigation
            project_name: navigation
            tag: large-monorepo:navigation
          - folder: ticket-booking
            project_name: ticket-booking
            tag: large-monorepo:ticket-booking
          - folder: warp-drive-manager
            project_name: warp-drive-manager
            tag: large-monorepo:warp-drive-manager

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Checkmarx One Scan for ${{ matrix.project_name }}
        uses: checkmarx/ast-github-action@8e887bb93dacc44e0f5b64ee2b06d5815f89d4fc
        with:
          base_uri: https://ast.checkmarx.net
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          cx_tenant: ${{ secrets.CX_TENANT }}
          additional_params: >-
            --report-format sarif 
            --output-path . 
            -s ./${{ matrix.folder }} 
            --project-name ${{ matrix.project_name }} 
            --project-tags ${{ matrix.tag }}

      - name: Upload SARIF for ${{ matrix.project_name }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: cx_result.sarif
